shamefullyHoist: true
engineStrict: true
minimumReleaseAge: 7200
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
  - svelte-preprocess
