shamefullyHoist: true
engineStrict: true
minimumReleaseAge: 1440
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - svelte-preprocess
allowBuilds:
  esbuild: true
  svelte-preprocess: true
