type HashedUrl {
  url: String! @unique
  hash: String! @unique
}

type Query {
  allHashedUrls: [HashedUrl]
  allHashedUrlsCount: Int! @resolver(name: "allHashedUrlsCount")
  hashedUrlFromHash(hash: String!): HashedUrl
  hashedUrlFromUrl(url: String!): HashedUrl
}
